/** @file
  Star Labs EC-only update container and target-information definitions.

  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

#ifndef STAR_LABS_EC_IFU_H_
#define STAR_LABS_EC_IFU_H_

#define STARLABS_EC_IFU_CONTAINER_SIZE  65824U
#define STARLABS_EC_IFU_HEADER_SIZE     32U
#define STARLABS_EC_IFU_POLICY_SIZE     192U
#define STARLABS_EC_IFU_IMAGE_SIZE      65536U
#define STARLABS_EC_IFU_SIGNATURE_SIZE  64U

#define STARLABS_EC_IFU_HEADER_MAGIC         "SL-ECIFU"
#define STARLABS_EC_IFU_POLICY_MAGIC         "SLIFUP01"
#define STARLABS_EC_IFU_DESCRIPTOR_MAGIC     "SLIFUD01"
#define STARLABS_EC_IFU_HEADER_VERSION       1U
#define STARLABS_EC_IFU_POLICY_VERSION       1U
#define STARLABS_EC_IFU_DESCRIPTOR_VERSION   1U
#define STARLABS_EC_IFU_DESCRIPTOR_SIZE      64U

#define STARLABS_EC_IFU_DESCRIPTOR_CHIP_OFFSET        10U
#define STARLABS_EC_IFU_DESCRIPTOR_FEATURES_OFFSET    11U
#define STARLABS_EC_IFU_DESCRIPTOR_BOARD_ID_OFFSET    12U
#define STARLABS_EC_IFU_DESCRIPTOR_IMAGE_MAJOR_OFFSET 14U
#define STARLABS_EC_IFU_DESCRIPTOR_IMAGE_MINOR_OFFSET 15U
#define STARLABS_EC_IFU_DESCRIPTOR_CODE_OFFSET        16U
#define STARLABS_EC_IFU_DESCRIPTOR_CODE_SIZE_OFFSET   20U
#define STARLABS_EC_IFU_DESCRIPTOR_INTERNAL_OFFSET    24U
#define STARLABS_EC_IFU_DESCRIPTOR_PERSISTENT_OFFSET  28U
#define STARLABS_EC_IFU_DESCRIPTOR_PERSISTENT_SIZE    32U
#define STARLABS_EC_IFU_DESCRIPTOR_MIRROR_OFFSET      36U
#define STARLABS_EC_IFU_DESCRIPTOR_MIRROR_SIZE        40U
#define STARLABS_EC_IFU_DESCRIPTOR_BOARD_NAME_OFFSET  44U
#define STARLABS_EC_IFU_DESCRIPTOR_BOARD_NAME_SIZE    20U
#define STARLABS_EC_IFU_DESCRIPTOR_FEATURES           0x03U
#define STARLABS_EC_IFU_DESCRIPTOR_CHIP_IT5570        1U
#define STARLABS_EC_IFU_DESCRIPTOR_CHIP_IT8987        2U

#define STARLABS_EC_IFU_POLICY_OFFSET       32U
#define STARLABS_EC_IFU_IMAGE_OFFSET        224U
#define STARLABS_EC_IFU_SIGNATURE_OFFSET    65760U

#define STARLABS_EC_IFU_POLICY_BOARD_ID_OFFSET          12U
#define STARLABS_EC_IFU_POLICY_CHIP_ID_OFFSET           14U
#define STARLABS_EC_IFU_POLICY_IMAGE_MAJOR_OFFSET       16U
#define STARLABS_EC_IFU_POLICY_IMAGE_MINOR_OFFSET       17U
#define STARLABS_EC_IFU_POLICY_MINIMUM_BATTERY_OFFSET   18U
#define STARLABS_EC_IFU_POLICY_POWER_FLAGS_OFFSET       19U
#define STARLABS_EC_IFU_POLICY_FLAGS_OFFSET             20U
#define STARLABS_EC_IFU_POLICY_FEATURES_OFFSET          24U
#define STARLABS_EC_IFU_POLICY_ROLLBACK_OFFSET          32U
#define STARLABS_EC_IFU_POLICY_INTERNAL_SIZE_OFFSET     40U
#define STARLABS_EC_IFU_POLICY_EXTERNAL_SIZE_OFFSET     44U
#define STARLABS_EC_IFU_POLICY_ERASE_SIZE_OFFSET        48U
#define STARLABS_EC_IFU_POLICY_IMAGE_REGION_OFFSET      52U
#define STARLABS_EC_IFU_POLICY_IMAGE_REGION_SIZE_OFFSET 56U
#define STARLABS_EC_IFU_POLICY_PRESERVE_OFFSET          60U
#define STARLABS_EC_IFU_POLICY_PRESERVE_SIZE_OFFSET     64U
#define STARLABS_EC_IFU_POLICY_IMAGE_SHA256_OFFSET      68U
#define STARLABS_EC_IFU_POLICY_KEY_ID_OFFSET            100U
#define STARLABS_EC_IFU_POLICY_MIRROR_SIGNATURE_OFFSET  132U
#define STARLABS_EC_IFU_POLICY_BOARD_NAME_OFFSET        148U
#define STARLABS_EC_IFU_POLICY_BOARD_NAME_SIZE          20U
#define STARLABS_EC_IFU_POLICY_RELEASE_OFFSET           168U
#define STARLABS_EC_IFU_POLICY_RELEASE_SIZE             24U

#define STARLABS_EC_IFU_POWER_AC_REQUIRED      0x01U
#define STARLABS_EC_IFU_POLICY_ALLOW_REINSTALL 0x00000001U
#define STARLABS_EC_IFU_REQUIRED_FEATURES      0x000000000000007fULL

#define STARLABS_EC_INTERNAL_SIZE     0x20000U
#define STARLABS_EC_EXTERNAL_SIZE     0x20000U
#define STARLABS_EC_ERASE_SIZE        0x400U
#define STARLABS_EC_PERSISTENT_OFFSET 0x1f800U
#define STARLABS_EC_PERSISTENT_SIZE   0x400U
#define STARLABS_EC_MIRROR_OFFSET     0x40U
#define STARLABS_EC_MIRROR_SIZE       0x10U

#define STARLABS_EC_CHIP_IT5570  0x5570U
#define STARLABS_EC_CHIP_IT8987  0x8987U

#define STARLABS_EC_TARGET_INFO_OFFSET    0x60U
#define STARLABS_EC_TARGET_INFO_SIZE      16U
#define STARLABS_EC_TARGET_INFO_MAGIC     "SLIF"
#define STARLABS_EC_TARGET_INFO_VERSION   1U
#define STARLABS_EC_TARGET_INFO_FEATURES  0x0007U

#define STARLABS_EC_VERSION_MAJOR_OFFSET   0x00U
#define STARLABS_EC_VERSION_MINOR_OFFSET   0x01U
#define STARLABS_EC_MIRROR_REQUEST_OFFSET  0x05U
#define STARLABS_EC_MIRROR_REQUEST         0xaaU
#define STARLABS_EC_POWER_STATE_OFFSET     0x80U
#define STARLABS_EC_BATTERY_PERCENT_OFFSET 0x93U
#define STARLABS_EC_POWER_AC_PRESENT       0x01U
#define STARLABS_EC_POWER_BATTERY_PRESENT  0x02U

#endif
