#!/usr/bin/env sh
#
# SPDX-License-Identifier: GPL-2.0-only

# DESCR: Check that GCC attributes use coreboot helper macros

LINTDIR="$(
  cd -- "$(dirname "$0")" > /dev/null 2>&1 || return
  pwd -P
)"

# shellcheck source=helper_functions.sh
. "${LINTDIR}/helper_functions.sh"

${GREP_FILES} -nI "__attribute__" Kconfig Makefile src include util tests 2>/dev/null | \
	grep -Ev '^(include/uefi.h|util/lint/checkpatch.pl|util/lint/lint-stable-027-attribute-helpers):' | \
	sed -e 's,^,Use coreboot attribute helper macros instead of raw GCC attributes: ,'
