#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# DESCR: Check that source files are not executable

LINTDIR="$(
  cd -- "$(dirname "$0")" > /dev/null 2>&1 || return
  pwd -P
)"

# shellcheck source=helper_functions.sh
. "${LINTDIR}/helper_functions.sh"

# Exit if the code isn't in a git repo
if [ "${IN_GIT_TREE}" -eq 0 ]; then
	exit 0
fi

${GIT} ls-files -s src include tests util | grep "^100[7531][7531][7531] " | cut -f2- | \
	grep -Ev "^(util/lint/|.*\.sh$)" | \
	sed -e "s,^.*$,File & has one or more executable bits set in the file permissions.,"
